w10d01/dragonball-demo/config/routes.rb
Rails.application.routes.draw do
  resources :comments
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # get 'login', to: 'users#login'

  # resources :planets

  # resources :characters

  resources :planets do
    resources :characters
  end
end

w10d01/dragonball-demo/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

w10d01/dragonball-demo/app/models/character.rb
class Character < ApplicationRecord
  belongs_to :planet # character.planet
end

w10d01/dragonball-demo/app/models/comment.rb
class Comment < ApplicationRecord
end

w10d01/dragonball-demo/app/models/planet.rb
class Planet < ApplicationRecord
  has_many :characters # planet.characters
end

w10d01/dragonball-demo/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

w10d01/dragonball-demo/app/controllers/characters_controller.rb
class CharactersController < ApplicationController
  def index
    planet_id = params[:planet_id] # req.params.planet_id

    @planet = Planet.find(planet_id)
    @characters = @planet.characters
  end
end

w10d01/dragonball-demo/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: %i[ show edit update destroy ]

  # GET /comments or /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1 or /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments or /comments.json
  def create
    @comment = Comment.new(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to comment_url(@comment), notice: "Comment was successfully created." }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1 or /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to comment_url(@comment), notice: "Comment was successfully updated." }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1 or /comments/1.json
  def destroy
    @comment.destroy

    respond_to do |format|
      format.html { redirect_to comments_url, notice: "Comment was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def comment_params
      params.fetch(:comment, {})
    end
end

w10d01/dragonball-demo/app/controllers/planets_controller.rb
class PlanetsController < ApplicationController
  def index
    @planets = Planet.all
    # render('index')
  end
end

w10d01/dragonball-demo/app/helpers/application_helper.rb
module ApplicationHelper
end

w10d01/dragonball-demo/app/helpers/characters_helper.rb
module CharactersHelper
end

w10d01/dragonball-demo/app/helpers/comments_helper.rb
module CommentsHelper
end

w10d01/dragonball-demo/app/helpers/planets_helper.rb
module PlanetsHelper
end

w10d01/dragonball-demo/app/views/characters/_character.html.erb
<div class="character">
  <h2>Name: <%= character.character %></h2>
  <h2>Race: <%= character.race %></h2>
  <h2>Planet: <%= character.planet.name %></h2>
</div>

w10d01/dragonball-demo/app/views/characters/index.html.erb
<h1>All the characters from <%= @planet.name %>!</h1>

<a href="/planets">Planets</a>
<%= link_to 'Planets', '/planets' %>
<%= link_to 'Planets', planets_path %>

<%= render @characters %>

w10d01/dragonball-demo/app/views/comments/_form.html.erb
<%= form_with(model: comment) do |form| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
        <% comment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

w10d01/dragonball-demo/app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

w10d01/dragonball-demo/app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Comments</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

w10d01/dragonball-demo/app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Back', comments_path %>

w10d01/dragonball-demo/app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

w10d01/dragonball-demo/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Dragonball</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

w10d01/dragonball-demo/app/views/planets/index.html.erb
<h1>All the planets!</h1>

<% @planets.each do |planet| %>
  <div class="planet">
    <h2>Planet: <%= planet.name %></h2>
    <%= link_to 'All the characters', planet_characters_path(planet) %>
  </div>
<% end %>